- sys/cnf_mint.c
- sys/info.c
- sys/init.c
- sys/init.h
- sys/kernget.c
- sys/mint/ktypes.h
- sys/mint/ssystem.h
- sys/ssystem.c
Don't hardcode bootlog file as "C:/mint/boot.log", use "\<sysdir\>/bootlog" (or "\<mchdir\>/boot.log" if present) instead.
> Don't hardcode bootlog file as "C:/mint/boot.log"

- tools/toswin2/Makefile
- tools/toswin2/ansicol.c
- tools/toswin2/config.c
- tools/toswin2/console.c
- tools/toswin2/console.h
- tools/toswin2/event.c
- tools/toswin2/main.c
- tools/toswin2/proc.c
- tools/toswin2/textwin.c
- tools/toswin2/tw-call/Makefile
- tools/toswin2/tw-call/tw-call.c
FIXED: crash / memory violation on repeated execution
FIXED: logging into the log file (correct checkbox state, checking for errors, fixed conf loading ...)
NEW: "Log console output" enables logging even without a console window opened
NEW: "Open on output" does open the console window in all cases (unlike previous behaviour when it opened only an iconified window)
FIXED: opening a bogus window if TW2 is started for the first time via tw-call
Plus various cleanups.
> Toswin2 fixes

- CONFIGVARS
- tools/nohog2/Makefile
Curious if this works:
Dear @freemint/kernel 
meant as a template for (optionally) linking of MiNT tools (that don't need POSIX) against libcmini instead of mintlib.
For the nohog2.acc, this ends up in a reduction of the executable file from about 108 kB (mintlib) to 5268 bytes without loss of functionality.
Just build (from within the nohog2 directory) with
`M68K_ATARI_MINT_CROSS=yes LIBCMINI=yes make`
I also took the freedom to make the Makefile ColdFire-aware:
`M68K_ATARI_MINT_CROSS=yes LIBCMINI=yes CPU=v4e make`
will create a ColdFire executable.
This could also be added to other tools if it became general consensus that this is the way to go.
Get libcmini from AtariForge:
`svn co http://atariforge.org/svn/libcmini`
should be done from the same directory your freemint directory …
> enable optional link to libcmini instead of mintlib

- tools/cops/cpx.h
@vinriviere 's toolchain uses older gemlib so the travis build didn't catch it :-/
> Fix building with gemlib 0.44.x

- .gitignore
- tools/Makefile
I'm not sure why there were disabled but even if they are broken (from functionality point of view; they build fine) it's better someone let it report than hide it.
> Enable compilation of strace and swkbdtbl.

- tools/mintload/mintloader.c
This works thanks to the shared source tree and it's much more helpful. The idea is to update/replace only mintload.prg in AUTO and not care about the platform on which the loader is executed. In the future, this opens the door for memory initialisation, MMU setup etc.
> mintloader's default path is not \\mint but <SYSDIR>.

- RULES
- sys/RULES
- sys/libkern/asm/Makefile.objs
- tools/IO/bswap.h
- tools/crypto/md5.c
- tools/toswin2/Makefile
- tools/toswin2/tw-call/Makefile
- xaaes/src.km/RULES
All it took was to move it into the toplevel `RULES`.
Toplevel `make CPU=xxx` doesn't work of course but now you can use the `CPU` variable pretty much anywhere, if you know what are you doing. Doesn't make #12 resolved but it's a little bit closer.
P.S. Surprisingly, many build scripts override `$(CPU)` (like `libkern`) for their needs, although not all of them. So maybe the next step would be to ensure that the `$(CPU)` is honoured where appropriate else override with the correct/desired value.
> Enable `make CPU=xxx` also for tools

- sys/usb/src.km/loader/loader.c
- tools/mintload/mintloader.c
- xaaes/src.km/xaloader/xaloader.c
Cut neutral (easily agreeable) stuff from #20 and take it a bit closer to #12.
I remember times when you could choose whether you want to load xaaes.km or CPU-specific variant (having xaaes030.km in the same directory), this seems to have disappeared somewhere.
This PR first looks for {xaaes,usb}\<CPU\>.km and if not found, falls back into {xaaes,usb}.km. So if anyone decides to fix #12 or just make his own CPU distro, he wouldn't need to think about proper kernel module name, just use default.
This PR also forces loading mint000.prg via mintloader in case cookie jar is not found, I never really understood why we should want to load mint.prg in such case. Also, mintv4e.prg target is added.
> Reintroduce the default loader targets

- sys/sockets/xif/svethlana/svethlana.c
- look for svethlan.inf not only in $SYSDIR but also on boot drive
- don't use 01:02:03:04:05:07 as default mac addr, use 00:01:02:03:04:05 instead (to prevent mistreating it as a multicast addr)
> Backport fixes from the ethernat driver

- sys/arch/detect.S
- sys/arch/init_mach.c
- sys/arch/kernfs_mach.c
- sys/global.c
- sys/global.h
- sys/init.c
This forces the _CPU coookie to 68040, as this processor has the most
complete instruction set. This is recommended by the Apollo Team.
> Add Apollo 68080 detection

- sys/Makefile.objs
- sys/buildinfo/cdef.sh
- sys/info.c
The generated cdef.h file contains target specific strings, and belongs in the .compile directory. This also prevents it from being overwritten by parallel makes.
> Generate cdef.h in target specific .compile_* directory

- .gitignore
This is necessary when cross-building on Windows.
> Add *.exe to .gitignore

- sys/dos.c
If an unpriviledged user would call Shutdown(), a static
flag remains set, preventing root from shutting down
the system.
> Reset static shutdown flag when Shutdown() returns

- sys/dosfile.c
- sys/fatfs.c
- sys/kerinfo.c
- sys/mint/kerinfo.h
- sys/ramfs.c
- sys/tosfs.c
- sys/xfs/aranym/aranym_fsdev.c
- sys/xfs/ext2fs/ext2dev.c
- sys/xfs/hostfs/hostfs_dev.c
- sys/xfs/hostfs/hostfs_nfapi.h
- sys/xfs/hostfs/hostfs_xfs.c
- sys/xfs/isofs/isofs.c
- sys/xfs/minixfs/minixdev.c
- sys/xfs/skeleton/dummy.c
File locking may require to have to suspend the process,
so the hostfs part in the emulator will never be able to
emulate file locking, since it does not have any notice of
MiNT processes. This must be done by hostfs.xfs.
File locking is eg. used by rpm, which will fail without this.
> Support file locking in hostfs

- sys/xdd/uart/pc16550.c
As seen in the mailing list, this fixes the build break introduced in #65 and cleans up some of the asm mess.
> Get rid of the asm interrupt handler

- sys/xfs/hostfs/hostfs_dev.c
The MetaDOS driver for Aranym (hostfs.dos) currently is compiled
by re-using parts of the hostfs driver of MiNT, but is not
really a mint filesystem and cannot use the locking functions.
> Do not use locking function when compiling the MetaDOS driver

- sys/keyboard.c
When the basic debug level is set (DEBUG) this one echoes every single key press what leads to a pretty verbose output which is not very useful.
> Lower IKBD debug output level

- sys/libkern/asm/blockcopy.S
- sys/libkern/asm/memset.S
This is supposed to fix #99.
Not sure about applying $(KERNELDEFAULTDEFS) ? Do we them in libkern?
> libkern should only depend on CPU type

- sys/usb/src.km/udd/keyboard/usb_keyboard.c
This makes a modified CKBD (keyboard utility) work with the USB keyboard.
@Perdrix24 reported that CKBD ("Composed Characters Keyboard Driver", https://github.com/ggnkua/Atari_ST_Sources/tree/master/C/Pascal%20Fellerich/COMPOSE/DRIVER/1_5) would not work with the USB keyboard driver. Most of it is better fixed in CKBD itself, which is what I have done. I will release the modified version of CKBD soon.
However, a small change is required to the USB keyboard driver, as well. Since CKBD hooks into the ACIA interrupt, this needs to be called _after_ posting the scancodes to TOS. The call was originally there to be able to reset the Nova screensaver with the USB keyboard. I have verified that moving the call has no impact on the Nova screensaver.
> Call into ACIA interrupt only after posting scancodes to TOS.

- sys/usb/src.km/global.h
During USB device driver development, I sometimes need to specifically debug the TOS versions of the drivers. This PR adds TOS support for the DEBUG and ALERT macros used in the code.
Debug output can be enabled with the DEV_DEBUG define, like in the MiNT version of the drivers and will print to the console.
> Add debug output support for TOS USB drivers.

- sys/usb/src.km/global.h
Previously setcookie() would crash with a bus error when no cookie jar existed, i.e., when the pointer to the jar was NULL. This happens on TOS 1.0x when the user does not load anything that creates a cookie jar prior to USB.PRG. 
Now USB.PRG will print an error message instead, like it already did when the jar was full.
> Make setcookie() fail and not crash if no jar exists.

- sys/KERNELDEFS
A smaller quantum is anyways defined in sys/mint/mem.h if the M68000 macro is set
> Remove unused QUANTUM_SMALLER macro from KERNELDEFS 

- sys/arch/detect.S
- sys/arch/detect.h
- sys/arch/init_mach.c
- sys/global.c
- sys/global.h
- sys/mint/ktypes.h
- sys/mmudefs.h
I was a bit bored so I finally took a look on one bug I had introduced in commit 820a13a0. According to @th-otto's finding in the TOS sources, _FPU 6888x bits are reserved for co-processor mode only: https://mikro.naprvyraz.sk/mint/freemint-list/Week-of-Mon-20170306/000808.html.
So I have finally fixed it (reverted back to original behaviour), i.e. if there is a SFP-004 compatible hardware detected, it sets only bit 16 in `_FPU` cookie value.
However since I love the feature of telling me which FPU have I connected via memory mapped mode, I have extended the original approach so now it properly detects even configurations like MegaSTE + 68881 + PAK68/3 (68030+68882).
Tested on Falcon+68882/CT60, MegaSTE+68881 and MegaSTE+68882.
> Fix _FPU cookie and improve SFP-004 handling

- xaaes/src.km/cnf_xaaes.c
- xaaes/src.km/example.cnf
- xaaes/src.km/k_init.c
- xaaes/src.km/xa_types.h
NVDI/ET4000 loads additional files by opening the physical workstation from current boot drive. This didn't work as it has been set to U: early on.
Investigation & fix courtesy of Christian Zietz.
Fixes #141.
> Fix NVDI/ET4000 handling

- sys/usb/src.km/udd/hid/tablet/Makefile
... like the other USB drivers already have.
> Add 'strip' and 'help' targets to USB tablet Makefile

- sys/xdd/scc/Makefile
The MegaSTE has an SCC, too. But scc.xdd was always being built for the 68020-60 and, thus, hung on the MegaSTE. I successfully tested the newly built scc.xdd on my MegaSTE.
Note: Imho, scc.xdd does not warrant per-CPU-builds. Therefore, it's acceptable that now the TT version of FreeMiNT will also get a scc.xdd built for 68000 and upwards.
Fixes #152
> Build scc.xdd for 68000 CPU

- sys/usb/src.km/udd/storage/usb_scsidrv.c
Not all USB mass storage devices support this, some crash rather
badly. HDDRIVER's HDDRUTIL program sends this command, so it's
blocked at the driver level. Note that this does not restrict
the drivers ability to handle multiple-LUN devices such as card
readers.
This was a regression introduced with commit c176b37363f6bc6df38b400d0828bd482a338d6d.
> USB: storage: Ignore REPORT_LUN command

- sys/filesys.c
As mentioned in #225, the special _MINTHAT.PRG_ imho only serves a purpose if it works with Hatari's GEMDOS drive emulation. As there is no BIOS device, media change detection and, thus, ultimately every drive access would fail with ENODEV (-15). (This can be seen in my first screenshot posted in #225.) 
Note that a similar change was introduced by Helmut K via commit 44341fef3869c45d805964ccbe2bae7204951582 but later reverted with commit 2dfde1b15202fca5f4c6ceeacce5cec6087b17d0.
> Make OLDTOSFS work with Hatari's GEMDOS drive emulation

- sys/usb/src.km/udd/hid/keyboard/usb_keyboard.c
Found via a Lightning VME customer complaint: When no USB keyboard is connected but the USB keyboard driver is loaded, pressing the CapsLock key on the Atari keyboard triggers a call (via `set_led()`) to a non-existent USB device, ultimately crashing the driver with a bus error. 
This PR fixes the regression introduced with commit efa812ca354a8a6dfc65782466241ea7a366c0da.
> USB kbd: Don't synchronize CapsLock LED when no USB kbd is connected

- xaaes/src.km/trnfm.c
Fixes #171.
That whole file is a huge mess so I'm just hoping this doesn't break something else. fVDI @ 16-bit seems to be still working correctly, though.
> Fix broken palette remapping in 8bpp mode

- sys/Makefile.objs
- sys/arch/kernel.S
- sys/arch/magic/genmagic.c
- sys/arch/syscall.S
- sys/dosmem.c
- sys/mint/proc.h
- xaaes/src.km/k_init.c
This is my take on #22 . There were two separate issues with it:
- syscall context was no longer saved as expected: since the introduction of reentrant syscalls the PC in the `ctxt` struct wouldn't belong to the last caller (TOS VDI routine in our case) but to the user application calling `v_opnvwk` (i.e. the malloc() call would be made while [the in_kernel flag](https://github.com/freemint/freemint/blob/master/sys/arch/syscall.S#L699) is already true and not saving any context)
- xaaes.km is a kernel module and therefore all functions (incl. [its v_opnvwk](https://github.com/freemint/freemint/blob/master/xaaes/src.km/k_init.c#L726)) are always called with `in_kernel` flag set so no new context is built/saved either.
As you can see, I have solved it via an addition flag, `in_vdi`, which …
> Fix TOS 3/4 VDI with memory protection

- xaaes/src.km/k_init.c
This caused device to be set to zero (TT) or video mode set to be zero without using device = 1 (Falcon).
See https://github.com/freemint/freemint/issues/250#issuecomment-1100628972.
Verified to fix the regression on both TT and Falcon.
> Fix xaaes.cnf without explicit video/modecode/screendev values

- sys/KERNELDEFS
Since b44c975ecbc4a36cc2d90251622e24650c2852d4 from @czietz we have the GEMDOS FAT driver working correctly with FreeMint.
Tested FreeMint with the GEMDOS FAT driver and Hatari GEMDOS emulation, this works correctly 
Outside the Hatari usage, using the GEMDOS FAT driver allows to workaround this bug in the Teradesk and FreeMint XFS FAT interaction: https://github.com/freemint/freemint/issues/155#issuecomment-636081860.
Tested with EmuTOS 1.0.1 and TOS 2.06
> Remove warning about  -DOLDTOSFS pending removal

- xaaes/src.km/k_init.c
This leads to random crashes if NVDI is chained with fVDI.
Reported by @wongck68 in https://groups.google.com/g/aranym/c/iyeFnaoSMeU/m/Gjnw7ODOBAAJ. Seemingly caused by @shoggoth77's https://github.com/freemint/freemint/commit/3223f88c432f07b5572d225904659b7d97143c0f but I've nailed down to [presence](https://github.com/freemint/freemint/blob/2b8d5dbcd79e6136765a28192742d64876b7605c/xaaes/src.km/k_init.c#L592) of one `long` on the stack which disappeared after PeP's changes.
First I thought that this is easily fixable by increasing supervisor stack size in https://github.com/freemint/freemint/blob/master/sys/mint/proc.h#L89 since `k_main` is created as a kernel thread but nope, it is some TOS calling magic (one can see a crash note `exception 10 for AESSYS pc:1249C24 addr:E00000` just …
> Free some space on SSP when calling v_opnwk

- .scripts/util.sh
Note: It is disabled (as picowifi.xix) by default.
> Add PicoWifi driver to builds

- sys/arch/kernel.S
- sys/arch/magic/genmagic.c
- sys/arch/syscall.S
- sys/mint/proc.h
- sys/proc.c
While investigating a fix for https://github.com/freemint/freemint/commit/b3214578 I noticed one inefficiency - we call [enter_kernel()](https://github.com/freemint/freemint/blob/master/sys/arch/kernel.S#L63) basically for no reason. Instead of just `bset #0x7,_in_kernel` we additionally set the same flag for the current process. However this process flag is never really used, except one debug output.
Considering how often this function gets called from trap handlers it could save quite a few cycles.
> Remove proc::in_kern flag

- CONFIGVARS
When enabled (what is with -O2 by default), one can observe unexpected and random freezes when downloading and uploading larger chunks to/from Atari (typically it is visible with files >10 MB).
This has been reported numerous times and basically all reports claim that this wasn't the case with older kernels. And indeed, 1.16.1b kernel doesn't suffer from this issue while 1.17.0 does.
So what changed? The official compiler did. 1.17.0 and all later releases have been compiled with 4.6.4 and later 7.5.0. And since it was gcc 4.x which introduced the aggressive optimizations... we have the answer.
Change the optimization level for the whole project, later we can decide what parts can have it enabled again.
> Disable strict aliasing

- sys/cookie.h
- sys/sockets/xif/svethlana/svethlana.c
For the hundredth time I spent half an hour of my life thinking why svethlan.xif is crashing on my CT60. And it is because it calls `ct60_vmalloc` provided by `SV_XBIOS.PRG`. Without `SV_XBIOS.PRG` present it crashes on a fatal error without any further information.
> Print error message instead of crashing

- xaaes/src.km/xa_defs.h
WIDGNAME ("xaaeswdg.rsc") is defined twice in the same file
> Remove duplicate WIDGNAME

- sys/arch/detect.S
- sys/arch/init_mach.c
Fixed broken FPU detection for 68060 EC/LC variants, it was returning the PCR register value instead of 0.
Avoid doing SFP-004 detection on 68020+ machines.
I am unsure if this is the correct way to go about it but that thing only exist on 000/010 equipped machines anyway.
I'd like to avoid the detection for the same reason as was done for 68080/Vampire but wasn't keen on adding yet another ifdef build config.
> FPU Detect fixes

- sys/arch/060sp/Makefile
- sys/arch/060sp/mint060sp.S
The Motorola 060 support package emulates the missing Integer as well as Fpu instructions, thus:
- Removed complaints when using on LC/EC and have it install the integer part.
- Renamed the executable from fpu060sp -> 060sp for the same reason.
In addition:
- Fixed broken 68060 detection.
- Fixed a couple of callout functions.
Should this executable be built and distributed with the 060 Freemint builds?
CT60 TOS has the 060 isp/fpsp built in already but for other hardware running EmuTos this is handy.
Preferably, this should come with EmuTOS builds rather than Freemint since it's equally useful when running EmuTOS only.
> mint060sp (motorola 060isp/fpsp)

- xaaes/src.km/app_man.c
This fixes a surprisingly rare crash when S.focus == NULL. It's possible that it breaks some scenario:
- commit 0978888e explicitly changed `top->owner` to `S.focus->owner` which is really suspicious because not only `top->keypress` check was kept but also the body still had the original condition (`top->owner == client && top->keypress`)
- commit 62947f1e extended the body with `S.focus && S.focus->owner == client`, perhaps to address the inconsistency but didn't add a NULL check and also kept `top->owner == client && top->keypress` intact.
This leads me to believe that actually both conditions are valid and the change from `top->owner` to `S.focus->owner` was done in a hurry without thinking it through.
Fixes #346.
===
As you can see, in the end it was very obvious but I was totally …
> Fix a null pointer crash

- .scripts/util.sh
- sys/console.c
- sys/dosfile.c
- sys/info.h
- sys/k_fds.c
- sys/sockets/xif/Makefile
- sys/sockets/xif/ppp.c
- sys/sockets/xif/serial.c
The commit in question assumed that the only use of O_GLOBAL is inside
slip.xif. However this is not true: it was used in both N.AES and AES
4.1 (and perhaps others) as a way of accessing the console device from
AES by every process.
Roughly, it works like this in AES 4.1:
- "MiNT" (the kernel) opens /dev/console for read/write and stores the
file handle as CON:
- "AESSYS" opens /dev/console for read/write with O_GLOBAL and gets a
file handle as if it were "MiNT"
- ("AESSYS" somehow distributes returned file handle to everyone
interested, perhaps as "this is the console device")
- everyone can now read and write from/to that file handle as if they
were all root processes (i.e. "AESSYS" is treated as "MiNT" and so are
others like "NEWDESK" or "SCREEN")
Narrow the O_GLOBAL handling only to …
> Partially revert commit 9668d67

- sys/sockets/xif/v4net/Makefile
Replace 68000 target to 68040, this driver is only for V4SA This change reduce highly size and speed up a lot the driver.
> 040 target

- sys/arch/info_mach.c
- sys/arch/init_mach.c
- sys/cookie.h
- sys/init.c
- sys/mint/ktypes.h
- sys/xdd/mfp/mfp.c
Some initial support for Raven Atari clone.
- recognise it as a machine type
- skip SFP detection since it cannot bus error on the tested address and 060FPU+SFP in the _FPU cookie will confuse certain programs
- page0 protection in the same way as Hades and Milan
- mfp.xdd can work on this machine
> Adding Raven specific support
